name: Man10Janken
version: '${project.version}'
main: github.io.jpbtk.Man10Janken
api-version: 1.19
commands:
  mja:
    description: Play Janken
    usage: /<command> [rock|paper|scissors]
    aliases: [j]
